---

- name: Check if .zshrc file is present
  stat:
    path: "~/.zshrc"
  register: zshrcpath

- name: Skip if .zshrc file is not present
  debug: msg="No .zshrc file found... skipping"
  when: zshrcpath.stat.exists == false
  ignore_errors: yes

- name: Backup .zshrc file if present
  synchronize:
    src: "~/.zshrc"
    dest: "~/.zshrc.{{ ansible_date_time.date }}.bak"
  become: no
  when: zshrcpath.state.exists == true
